import { useState } from 'react'

const RACI_STYLES = {
  R: 'bg-green-100 text-green-800 border-green-200 font-bold',
  A: 'bg-navy/10 text-navy border-navy/20 font-bold',
  C: 'bg-yellow-100 text-yellow-800 border-yellow-200 font-semibold',
  I: 'bg-gray-100 text-gray-500 border-gray-200',
}

const CAT_COLORS = [
  'text-blue-700 bg-blue-50',
  'text-purple-700 bg-purple-50',
  'text-green-700 bg-green-50',
  'text-red-700 bg-red-50',
  'text-orange-700 bg-orange-50',
]

function RACIBadge({ code }) {
  if (!code) return <span className="inline-block w-7 h-7" />
  return (
    <span className={`inline-flex items-center justify-center w-7 h-7 rounded-md border text-xs ${RACI_STYLES[code] || 'bg-gray-100 text-gray-400 border-gray-200'}`}>
      {code}
    </span>
  )
}

function RACITable({ category, colorClass }) {
  const [open, setOpen] = useState(true)
  if (!category?.activities?.length) return null
  const roles = Object.keys(category.activities[0]?.raci || {})
  const activeRoles = roles.filter(r => category.activities.some(a => a.raci?.[r]))

  return (
    <div className="bg-surface border border-border rounded-xl overflow-hidden">
      <button onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-bg transition-colors text-left">
        <span className={`text-sm font-semibold ${colorClass?.split(' ')[0] || 'text-text'}`}>{category.category}</span>
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted">{category.activities.length} activities</span>
          <svg className={`w-4 h-4 text-muted transition-transform ${open ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>
      {open && (
        <div className="overflow-x-auto border-t border-border">
          <table className="w-full text-xs">
            <thead>
              <tr className="bg-surface/80 border-b border-border">
                <th className="text-left px-4 py-3 text-muted font-medium min-w-[200px]">Activity</th>
                {activeRoles.map(role => (
                  <th key={role} className="px-2 py-3 text-center text-muted font-medium min-w-[90px] leading-tight">{role}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {category.activities.map((item, i) => (
                <tr key={i} className={`border-b border-border last:border-0 ${i % 2 === 0 ? 'bg-bg' : 'bg-surface'}`}>
                  <td className="px-4 py-3 text-text font-medium leading-snug">{item.activity}</td>
                  {activeRoles.map(role => (
                    <td key={role} className="px-2 py-3 text-center">
                      <RACIBadge code={item.raci?.[role] || ''} />
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

export default function RACIOutput({ result, formData, onRestart }) {
  const [copied, setCopied] = useState(false)

  const formatAsText = () => {
    let text = `AI Project RACI Matrix — ${formData.productName}\n${'='.repeat(60)}\n`
    text += `Org Size: ${formData.orgSize} | Stage: ${formData.deploymentStage}`
    if (formData.industry) text += ` | Industry: ${formData.industry}`
    text += `\n\nOVERVIEW\n${'-'.repeat(40)}\n${result.summary}\n`
    text += `\nROLES\n${'-'.repeat(40)}\n`
    result.roles?.forEach(r => { text += `${r.title} (${r.department}): ${r.description}\n` })
    result.categories?.forEach(cat => {
      text += `\n${cat.category.toUpperCase()}\n${'-'.repeat(40)}\n`
      const roles = cat.activities[0] ? Object.keys(cat.activities[0].raci || {}) : []
      const active = roles.filter(r => cat.activities.some(a => a.raci?.[r]))
      text += `Activity | ${active.join(' | ')}\n`
      cat.activities.forEach(item => {
        text += `${item.activity} | ${active.map(r => item.raci?.[r] || '-').join(' | ')}\n`
      })
    })
    text += `\nKEY INSIGHTS\n${'-'.repeat(40)}\n`
    result.keyInsights?.forEach((ins, i) => { text += `${i + 1}. ${ins}\n` })
    text += `\nGenerated by kenrahuconsulting.com — AI RACI Builder`
    return text
  }

  const handleCopy = () => { navigator.clipboard.writeText(formatAsText()); setCopied(true); setTimeout(() => setCopied(false), 2000) }

  return (
    <div className="min-h-screen bg-bg px-6 py-16">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-surface border border-border rounded-full px-4 py-1.5 mb-4">
            <span className="w-2 h-2 rounded-full bg-green-500 inline-block"></span>
            <span className="text-muted text-sm">{result.roles?.length} roles · {result.categories?.length} activity categories</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-1">Your RACI Matrix</h2>
          <p className="text-muted text-sm">{formData.productName} · {formData.orgSize} · {formData.deploymentStage}</p>
        </div>

        <button onClick={handleCopy} className="w-full flex items-center justify-center gap-2 bg-surface border border-border hover:border-navy text-text font-medium py-3 rounded-lg transition-colors text-sm mb-6">
          {copied
            ? (<><svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>Copied!</>)
            : (<><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>Copy Full Matrix</>)
          }
        </button>

        <div className="flex gap-3 flex-wrap mb-6">
          {[['R','Responsible','bg-green-100 text-green-800'],['A','Accountable','bg-navy/10 text-navy'],['C','Consulted','bg-yellow-100 text-yellow-800'],['I','Informed','bg-gray-100 text-gray-500']].map(([code, label, cls]) => (
            <span key={code} className={`inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full ${cls}`}>
              <strong>{code}</strong> {label}
            </span>
          ))}
        </div>

        <div className="bg-navy/5 border border-navy/20 rounded-xl p-5 mb-6">
          <p className="text-xs font-semibold text-navy uppercase tracking-widest mb-2">Stakeholder Overview</p>
          <p className="text-sm text-text leading-relaxed">{result.summary}</p>
        </div>

        {result.roles?.length > 0 && (
          <div className="bg-surface border border-border rounded-xl p-5 mb-6">
            <p className="text-xs font-semibold text-muted uppercase tracking-widest mb-4">Roles in This Matrix</p>
            <div className="grid sm:grid-cols-2 gap-3">
              {result.roles.map((role, i) => (
                <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-bg border border-border">
                  <div className="w-7 h-7 rounded-md bg-navy/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-navy">{i + 1}</span>
                  </div>
                  <div>
                    <p className="text-xs font-semibold text-text">{role.title}</p>
                    <p className="text-xs text-muted">{role.department}</p>
                    <p className="text-xs text-muted mt-0.5 leading-snug">{role.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-3 mb-6">
          {result.categories?.map((cat, i) => (
            <RACITable key={i} category={cat} colorClass={CAT_COLORS[i] || 'text-text bg-surface'} />
          ))}
        </div>

        {result.keyInsights?.length > 0 && (
          <div className="bg-surface border border-border rounded-xl p-5 mb-6">
            <p className="text-xs font-semibold text-muted uppercase tracking-widest mb-3">Key Insights & Gaps</p>
            <div className="space-y-3">
              {result.keyInsights.map((ins, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className="text-xs font-bold text-navy w-4 flex-shrink-0 mt-0.5">{i + 1}</span>
                  <p className="text-sm text-text leading-snug">{ins}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="bg-surface border border-border rounded-xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4 mb-6">
          <div>
            <p className="text-text text-sm font-medium">Need help running stakeholder alignment?</p>
            <p className="text-muted text-xs mt-0.5">I facilitate AI governance and RACI workshops for enterprise teams.</p>
          </div>
          <a href="https://calendly.com/kendale-rahul/30min" target="_blank" rel="noopener noreferrer"
            className="flex-shrink-0 bg-navy hover:bg-navy-dark text-white font-semibold px-5 py-2.5 rounded-lg transition-colors text-sm">
            Book a Free Audit →
          </a>
        </div>

        <div className="text-center">
          <button onClick={onRestart} className="text-muted text-sm hover:text-text transition-colors">← Build another RACI</button>
        </div>
      </div>
    </div>
  )
}
