import { useState } from 'react'

const CATEGORY_STYLES = {
  'Quick Win':     'bg-green-50 text-green-700 border-green-200',
  'Strategic Bet': 'bg-blue-50 text-blue-700 border-blue-200',
  'Pilot Later':   'bg-yellow-50 text-yellow-700 border-yellow-200',
  'Deprioritise':  'bg-red-50 text-red-700 border-red-200',
}

const CATEGORY_SECTIONS = [
  { key: 'quickWins',     label: 'Quick Wins',     desc: 'Build first — high value, low effort',      color: 'text-green-700', bg: 'bg-green-50 border-green-200' },
  { key: 'strategicBets', label: 'Strategic Bets', desc: 'Plan carefully — high value, higher effort', color: 'text-blue-700',  bg: 'bg-blue-50 border-blue-200' },
  { key: 'pilotLater',    label: 'Pilot Later',    desc: 'Validate assumptions first',                 color: 'text-yellow-700', bg: 'bg-yellow-50 border-yellow-200' },
  { key: 'deprioritise',  label: 'Deprioritise',  desc: 'Not worth the investment now',               color: 'text-red-700',   bg: 'bg-red-50 border-red-200' },
]

function ScoreBar({ value, invert = false }) {
  const display = invert ? 10 - value : value
  const pct = (display / 10) * 100
  const color = display >= 7 ? 'bg-green-500' : display >= 5 ? 'bg-yellow-500' : 'bg-red-500'
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-1.5 bg-border rounded-full overflow-hidden">
        <div className={`h-full rounded-full ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs text-muted w-4 text-right">{value}</span>
    </div>
  )
}

function UseCaseCard({ uc }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="bg-surface border border-border rounded-xl overflow-hidden">
      <button onClick={() => setOpen(o => !o)} className="w-full flex items-center justify-between px-5 py-4 hover:bg-bg transition-colors text-left">
        <div className="flex items-center gap-4">
          <span className="text-lg font-bold text-navy/30 w-6">#{uc.rank}</span>
          <div>
            <p className="text-sm font-semibold text-text">{uc.name}</p>
            <p className="text-xs text-muted mt-0.5">Priority Score: <span className="text-navy font-bold">{uc.priorityScore?.toFixed(1)}</span></p>
          </div>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0">
          <span className={`text-xs font-medium px-2.5 py-1 rounded-full border ${CATEGORY_STYLES[uc.category] || 'bg-bg text-muted border-border'}`}>{uc.category}</span>
          <svg className={`w-4 h-4 text-muted transition-transform ${open ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>
      {open && (
        <div className="px-5 pb-5 border-t border-border">
          <div className="pt-4 space-y-2 mb-4">
            {[['Business Impact', uc.businessImpact, false],['Implementation Effort', uc.implementationEffort, true],['Risk Level', uc.risk, true],['Data Availability', uc.dataAvailability, false],['Governance Complexity', uc.governanceComplexity, true]].map(([label, val, invert]) => (
              <div key={label} className="grid grid-cols-[150px_1fr] items-center gap-3">
                <span className="text-xs text-muted">{label}</span>
                <ScoreBar value={val} invert={invert} />
              </div>
            ))}
          </div>
          <div className="bg-bg rounded-lg p-3 border border-border">
            <p className="text-xs text-muted leading-relaxed">{uc.rationale}</p>
          </div>
        </div>
      )}
    </div>
  )
}

export default function PrioritizerOutput({ result, formData, onRestart }) {
  const [copied, setCopied] = useState(false)

  const formatAsText = () => {
    let text = `AI Use Case Prioritization Matrix\n${'='.repeat(50)}\n\n`
    if (formData.context) text += `Context: ${formData.context}\n`
    if (formData.industry) text += `Industry: ${formData.industry}\n`
    text += `AI Maturity: ${formData.maturity}\n\nSTRATEGIC RECOMMENDATION\n${'-'.repeat(30)}\n${result.summary}\n\n`
    CATEGORY_SECTIONS.forEach(({ key, label }) => {
      const items = result[key]
      if (items?.length > 0) text += `${label.toUpperCase()}: ${items.join(', ')}\n`
    })
    text += `\nRANKED USE CASES\n${'-'.repeat(30)}\n`
    result.rankedUseCases?.forEach(uc => {
      text += `\n#${uc.rank} ${uc.name} [${uc.category}] — Score: ${uc.priorityScore?.toFixed(1)}\n`
      text += `  Impact: ${uc.businessImpact} | Effort: ${uc.implementationEffort} | Risk: ${uc.risk} | Data: ${uc.dataAvailability} | Governance: ${uc.governanceComplexity}\n`
      text += `  ${uc.rationale}\n`
    })
    text += `\nGenerated by kenrahuconsulting.com — AI Use Case Prioritizer`
    return text
  }

  const handleCopy = () => { navigator.clipboard.writeText(formatAsText()); setCopied(true); setTimeout(() => setCopied(false), 2000) }

  return (
    <div className="min-h-screen bg-bg px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-surface border border-border rounded-full px-4 py-1.5 mb-4">
            <span className="w-2 h-2 rounded-full bg-green-500 inline-block"></span>
            <span className="text-muted text-sm">{result.rankedUseCases?.length} use cases scored and ranked</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-2">Your Prioritization Matrix</h2>
          {formData.context && <p className="text-muted text-sm">{formData.context}</p>}
        </div>

        <button onClick={handleCopy} className="w-full flex items-center justify-center gap-2 bg-surface border border-border hover:border-navy text-text font-medium py-3 rounded-lg transition-colors text-sm mb-6">
          {copied ? (<><svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>Copied!</>) : (<><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>Copy Full Matrix</>)}
        </button>

        <div className="bg-navy/5 border border-navy/20 rounded-xl p-5 mb-6">
          <p className="text-xs font-semibold text-navy uppercase tracking-widest mb-2">Strategic Recommendation</p>
          <p className="text-text text-sm leading-relaxed">{result.summary}</p>
        </div>

        <div className="grid grid-cols-2 gap-3 mb-8">
          {CATEGORY_SECTIONS.map(({ key, label, desc, color, bg }) => {
            const items = result[key] || []
            if (!items.length) return null
            return (
              <div key={key} className={`rounded-xl border p-4 ${bg}`}>
                <p className={`text-xs font-semibold uppercase tracking-widest mb-1 ${color}`}>{label}</p>
                <p className="text-muted text-xs mb-2">{desc}</p>
                <ul className="space-y-1">{items.map(name => <li key={name} className={`text-xs flex items-start gap-1.5 ${color}`}><span className="mt-1">·</span><span className="text-text">{name}</span></li>)}</ul>
              </div>
            )
          })}
        </div>

        <div className="mb-2">
          <p className="text-xs font-semibold text-muted uppercase tracking-widest mb-3">Full Ranked Matrix — click to expand</p>
          <div className="space-y-2">{result.rankedUseCases?.map(uc => <UseCaseCard key={uc.name} uc={uc} />)}</div>
        </div>

        <div className="bg-surface border border-border rounded-xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4 mt-6">
          <p className="text-muted text-xs">Generated by kenrahuconsulting.com · AI Use Case Prioritizer</p>
          <a href="https://calendly.com/kendale-rahul/30min" target="_blank" rel="noopener noreferrer" className="text-navy text-xs font-medium hover:underline">
            Want help building these? Book a free AI Audit →
          </a>
        </div>

        <div className="text-center mt-8">
          <button onClick={onRestart} className="text-muted text-sm hover:text-text transition-colors">← Prioritise another set</button>
        </div>
      </div>
    </div>
  )
}
