import { useState, useRef } from 'react'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

const SECTION_LABELS = {
  executiveSummary: 'Executive Summary',
  problemStatement: 'Problem Statement',
  strategicRationale: 'Strategic Rationale',
  automatedFunctions: 'Automated Functions',
  goalsAndMetrics: 'Goals & Metrics Framework',
  stakeholdersAndRoles: 'Stakeholders & Roles (RACI)',
  featureRequirements: 'Feature Requirements',
  governanceFramework: 'Governance Framework',
  securityAndCompliance: 'Security & Compliance',
  operatingModel: 'End-to-End Operating Model',
  reportsToCreate: 'Reports to Create',
  risksAndOpenQuestions: 'Risks & Open Questions',
}

export default function PRDOutput({ prd, formData, onRestart }) {
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)
  const outputRef = useRef(null)

  const formatAsText = () => {
    let text = `PRD: ${formData.productName}\n${'='.repeat(60)}\n\n`
    if (formData.oneLiner) text += `${formData.oneLiner}\n\n`
    Object.entries(prd).forEach(([key, content]) => {
      const label = SECTION_LABELS[key] || key
      text += `${label}\n${'-'.repeat(40)}\n${content}\n\n`
    })
    text += `\nGenerated by kenrahuconsulting.com — Enterprise AI PRD Generator`
    return text
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(formatAsText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadPDF = async () => {
    setDownloading(true)
    try {
      const canvas = await html2canvas(outputRef.current, {
        backgroundColor: '#F8FAFC',
        scale: 2,
      })
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width
      let position = 0
      const pageHeight = pdf.internal.pageSize.getHeight()

      while (position < pdfHeight) {
        pdf.addImage(imgData, 'PNG', 0, -position, pdfWidth, pdfHeight)
        position += pageHeight
        if (position < pdfHeight) pdf.addPage()
      }

      pdf.save(`PRD-${formData.productName.replace(/\s+/g, '-')}.pdf`)
    } catch (err) {
      console.error('PDF error:', err)
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="min-h-screen bg-bg px-6 py-16">
      <div className="max-w-3xl mx-auto">

        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-surface border border-border rounded-full px-4 py-1.5 mb-4">
            <span className="w-2 h-2 rounded-full bg-green-500 inline-block"></span>
            <span className="text-muted text-sm">Enterprise PRD Generated — 12 sections</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-2">{formData.productName}</h2>
          {formData.oneLiner && <p className="text-muted text-sm">{formData.oneLiner}</p>}
        </div>

        <div className="flex gap-3 mb-8">
          <button
            onClick={handleCopy}
            className="flex-1 flex items-center justify-center gap-2 bg-surface border border-border hover:border-navy text-text font-medium py-3 rounded-lg transition-colors text-sm"
          >
            {copied ? (
              <>
                <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy to Clipboard
              </>
            )}
          </button>

          <button
            onClick={handleDownloadPDF}
            disabled={downloading}
            className="flex-1 flex items-center justify-center gap-2 bg-navy hover:bg-navy-dark disabled:opacity-40 disabled:cursor-not-allowed text-white font-medium py-3 rounded-lg transition-colors text-sm"
          >
            {downloading ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                Downloading...
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                Download PDF
              </>
            )}
          </button>
        </div>

        <div ref={outputRef} className="space-y-4">
          <div className="bg-surface border border-border rounded-xl p-6">
            <p className="text-navy text-xs font-semibold uppercase tracking-widest mb-1">Product Requirements Document</p>
            <h1 className="text-xl font-bold text-text">{formData.productName}</h1>
            {formData.oneLiner && <p className="text-muted text-sm mt-1">{formData.oneLiner}</p>}
            <div className="flex flex-wrap gap-3 mt-3">
              <span className="text-xs bg-navy/10 text-navy px-2 py-1 rounded">Enterprise AI</span>
              <span className="text-xs bg-bg text-muted px-2 py-1 rounded border border-border">Timeline: {formData.timeline}</span>
              {formData.complianceRequirements && (
                <span className="text-xs bg-bg text-muted px-2 py-1 rounded border border-border">{formData.complianceRequirements}</span>
              )}
            </div>
          </div>

          {Object.entries(prd).map(([key, content]) => (
            <div key={key} className="bg-surface border border-border rounded-xl p-6">
              <h3 className="text-navy text-xs font-semibold uppercase tracking-widest mb-3">
                {SECTION_LABELS[key] || key}
              </h3>
              <div className="text-text text-sm leading-relaxed whitespace-pre-line">{content}</div>
            </div>
          ))}

          <div className="bg-surface border border-border rounded-xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-muted text-xs">Generated by kenrahuconsulting.com · Enterprise AI PRD Generator</p>
            <a
              href="https://calendly.com/kendale-rahul/30min"
              target="_blank"
              rel="noopener noreferrer"
              className="text-navy text-xs font-medium hover:underline"
            >
              Book a free AI PM consultation with Rahul →
            </a>
          </div>
        </div>

        <div className="text-center mt-8">
          <button onClick={onRestart} className="text-muted text-sm hover:text-text transition-colors">
            ← Generate another PRD
          </button>
        </div>

      </div>
    </div>
  )
}
