import { useState } from 'react'

const LAYERS = [
  { key: 'businessGovernance',    number: 1, title: 'Business Governance',    color: 'text-blue-700',  bg: 'bg-blue-50 border-blue-200' },
  { key: 'productGovernance',     number: 2, title: 'Product Governance',     color: 'text-purple-700', bg: 'bg-purple-50 border-purple-200' },
  { key: 'modelGovernance',       number: 3, title: 'Model Governance',       color: 'text-navy',      bg: 'bg-navy/5 border-navy/20' },
  { key: 'operationalGovernance', number: 4, title: 'Operational Governance', color: 'text-orange-700', bg: 'bg-orange-50 border-orange-200' },
  { key: 'riskAndCompliance',     number: 5, title: 'Risk & Compliance',      color: 'text-red-700',   bg: 'bg-red-50 border-red-200' },
]

function ChecklistLayer({ number, title, items, color, bg, checked, onToggle }) {
  const doneCount = items.filter((_, i) => checked[i]).length
  return (
    <div className={`rounded-xl border p-5 ${bg}`}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <span className={`text-xs font-bold w-4 ${color}`}>{number}</span>
          <h3 className={`text-sm font-semibold uppercase tracking-wide ${color}`}>{title}</h3>
        </div>
        <span className="text-xs text-muted">{doneCount}/{items.length}</span>
      </div>
      <div className="space-y-2">
        {items.map((item, i) => (
          <button key={i} onClick={() => onToggle(i)}
            className="w-full flex items-start gap-3 text-left group">
            <div className={`w-5 h-5 rounded border-2 flex-shrink-0 mt-0.5 flex items-center justify-center transition-all ${checked[i] ? 'bg-navy border-navy' : 'border-muted/40 group-hover:border-navy/50'}`}>
              {checked[i] && (
                <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              )}
            </div>
            <span className={`text-sm leading-snug transition-colors ${checked[i] ? 'text-muted line-through' : 'text-text'}`}>{item}</span>
          </button>
        ))}
      </div>
    </div>
  )
}

export default function GovernanceOutput({ result, formData, onRestart }) {
  const [checks, setChecks] = useState(() =>
    Object.fromEntries(LAYERS.map(l => [l.key, Array((result[l.key] || []).length).fill(false)]))
  )
  const [copied, setCopied] = useState(false)

  const toggleCheck = (layerKey, index) => {
    setChecks(prev => {
      const arr = [...prev[layerKey]]
      arr[index] = !arr[index]
      return { ...prev, [layerKey]: arr }
    })
  }

  const totalItems = LAYERS.reduce((sum, l) => sum + (result[l.key] || []).length, 0)
  const totalDone = LAYERS.reduce((sum, l) => sum + (checks[l.key] || []).filter(Boolean).length, 0)
  const pct = totalItems > 0 ? Math.round((totalDone / totalItems) * 100) : 0

  const formatAsText = () => {
    let text = `AI Governance Checklist — ${formData.productName}\n${'='.repeat(60)}\n`
    text += `Risk Level: ${formData.riskLevel} | Data Sensitivity: ${formData.dataSensitivity} | Stage: ${formData.deploymentStage}\n`
    if (formData.industry) text += `Industry: ${formData.industry}\n`
    text += `\nPRIORITY ACTIONS\n${'-'.repeat(40)}\n`
    result.priorityActions?.forEach((a, i) => { text += `${i + 1}. ${a}\n` })
    LAYERS.forEach(({ key, number, title }) => {
      const items = result[key] || []
      if (!items.length) return
      text += `\nLayer ${number}: ${title.toUpperCase()}\n${'-'.repeat(40)}\n`
      items.forEach(item => { text += `☐ ${item}\n` })
    })
    text += `\nGenerated by kenrahuconsulting.com — AI Governance Checklist`
    return text
  }

  const handleCopy = () => { navigator.clipboard.writeText(formatAsText()); setCopied(true); setTimeout(() => setCopied(false), 2000) }

  return (
    <div className="min-h-screen bg-bg px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-surface border border-border rounded-full px-4 py-1.5 mb-4">
            <span className="w-2 h-2 rounded-full bg-green-500 inline-block"></span>
            <span className="text-muted text-sm">{totalItems} items across 5 governance layers</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-1">Your Governance Checklist</h2>
          <p className="text-muted text-sm">{formData.productName} · {formData.riskLevel} Risk · {formData.deploymentStage}</p>
        </div>

        <div className="bg-surface border border-border rounded-xl p-5 mb-6">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold text-muted uppercase tracking-widest">Overall Progress</span>
            <span className="text-navy font-bold text-sm">{totalDone}/{totalItems} items</span>
          </div>
          <div className="h-2 bg-border rounded-full overflow-hidden">
            <div className="h-full bg-navy rounded-full transition-all duration-500" style={{ width: `${pct}%` }} />
          </div>
          <p className="text-muted/60 text-xs mt-2">{pct}% complete — check items off as you go</p>
        </div>

        <div className="flex gap-3 mb-6">
          <button onClick={handleCopy} className="flex-1 flex items-center justify-center gap-2 bg-surface border border-border hover:border-navy text-text font-medium py-3 rounded-lg transition-colors text-sm">
            {copied
              ? (<><svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>Copied!</>)
              : (<><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>Copy Checklist</>)
            }
          </button>
        </div>

        {result.priorityActions?.length > 0 && (
          <div className="bg-navy/5 border border-navy/20 rounded-xl p-5 mb-5">
            <p className="text-xs font-semibold text-navy uppercase tracking-widest mb-3">Priority Actions — Do These First</p>
            <div className="space-y-2">
              {result.priorityActions.map((action, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className="text-xs font-bold text-navy w-4 flex-shrink-0 mt-0.5">{i + 1}</span>
                  <p className="text-sm text-text leading-snug">{action}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-4 mb-6">
          {LAYERS.map(layer => (
            <ChecklistLayer
              key={layer.key}
              number={layer.number}
              title={layer.title}
              color={layer.color}
              bg={layer.bg}
              items={result[layer.key] || []}
              checked={checks[layer.key] || []}
              onToggle={(i) => toggleCheck(layer.key, i)}
            />
          ))}
        </div>

        <div className="bg-surface border border-border rounded-xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4 mb-6">
          <div>
            <p className="text-text text-sm font-medium">Need help implementing this?</p>
            <p className="text-muted text-xs mt-0.5">I run AI governance audits for enterprise product teams.</p>
          </div>
          <a href="https://calendly.com/kendale-rahul/30min" target="_blank" rel="noopener noreferrer"
            className="flex-shrink-0 bg-navy hover:bg-navy-dark text-white font-semibold px-5 py-2.5 rounded-lg transition-colors text-sm">
            Book a Free Audit →
          </a>
        </div>

        <div className="bg-surface border border-border rounded-xl p-4 flex items-center justify-between mb-8">
          <p className="text-muted text-xs">Generated by kenrahuconsulting.com · AI Governance Checklist</p>
        </div>

        <div className="text-center">
          <button onClick={onRestart} className="text-muted text-sm hover:text-text transition-colors">← Generate another checklist</button>
        </div>
      </div>
    </div>
  )
}
